on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install west and dependencies
        run: |
          pip install west
          west init -l zmk
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble \
            -- -DZMK_CONFIG=config \
               -DSHIELD="moNa2_R,rgbled_adapter"



#original jobs are below 
#jobs:
#  build:
#    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
#    with:
#      config-path: config